### PR TITLE
Do not store the compiled binary in Git

### PR DESCRIPTION
**Pull request by jboynes**
Although it's handy for people who just checkout out the repo, this clutters the repo history with large binary artifacts.

We should distribute this for users by publishing to a SNAPSHOT repo somewhere, or using alternative packaging like a Docker image.

### CODE REVIEW

**Comment by rob42** [comment]
As you say it was done to make things easier for noobs, just git clone and run. Otherwise it requires maven, jdk and build process etc. I am struggling with the workload now, and didnt want to complicate the project with two repos. But the bin image is a valid consideration. Wonder if its possible to automate it with a module or artifactory like integration?

**Comment by jboynes** [comment]
Opened #24 to set up automated distribution. I think we should stop checking the binary in anyway as it will rapidly bloat the size of the repo (a full copy it stored as part of every commit).

**Comment by rob42** [comment]
Ive changed the project to use jitpack.io which is a shortcut and more flexible way of doing maven releases. This means the all-in-one jar not  be commited anymore. Leaving the existing history so we dont disturb other forks.

**Comment by rob42** [comment]
Just realised there are other changes bundled in here - still need to go through them.

**Comment by rob42** [comment]
jitpack.io is working now which negates the need for the binaries to be stored in git. Most other changes (except travis) have been merged into the master separately, so closing this.
Pls add another separate travis pull request if required.

**Pull request closed without merging**
